# Generated by Django 4.2.4 on 2023-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfiles',
            name='input_file',
            field=models.FileField(max_length=300, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='convertedfiles',
            name='outpu_file',
            field=models.FileField(max_length=300, null=True, upload_to='docx_files/'),
        ),
    ]
