# Generated by Django 4.2.4 on 2023-10-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_file', '0002_alter_convertedfiles_input_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertedfiles',
            old_name='outpu_file',
            new_name='output_file',
        ),
    ]
