# Generated by Django 4.2.4 on 2023-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_file', '0003_rename_outpu_file_convertedfiles_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedfiles',
            name='input_path',
            field=models.FilePathField(null=True),
        ),
    ]
